const RentalRepository = require('../repositories/RentalRepository');
const penaltyCalculator = require('../../../src/utils/penaltyCalculator');
const invoiceGenerator = require('../../../src/utils/invoiceGenerator');
const helpers = require('../../../src/utils/helpers');
const logger = require('../../../src/utils/logger');

function formatRentalResponse(row) {
  if (!row) return null;
  return {
    rentalId: row.rental_id,
    customer: {
      userId: row.user_id,
      name: row.user_name || null,
      phone: row.user_phone || null,
      email: row.user_email || null
    },
    vehicle: {
      vehicleId: row.vehicle_id,
      registrationNumber: row.registration_number || null,
      modelName: row.model_name || null,
      vehicleType: row.vehicle_type || null,
      color: row.color || null
    },
    plan: row.plan_id ? {
      planId: row.plan_id,
      name: row.plan_name || null,
      rate: parseFloat(row.plan_rate || row.rate || 0),
      durationType: row.plan_duration_type || row.duration_type || null
    } : null,
    branches: {
      pickup: row.pickup_branch_id ? {
        branchId: row.pickup_branch_id,
        name: row.pickup_branch_name || null
      } : null,
      return: row.return_branch_id ? {
        branchId: row.return_branch_id,
        name: row.return_branch_name || null
      } : null
    },
    status: row.status,
    paymentStatus: row.payment_status,
    dates: {
      expectedStart: row.start_date,
      expectedEnd: row.end_date,
      actualStart: row.actual_start_time || null,
      actualEnd: row.actual_end_time || null
    },
    financials: {
      baseAmount: parseFloat(row.base_amount || 0),
      securityDeposit: parseFloat(row.security_deposit || 0),
      discountAmount: parseFloat(row.discount_amount || 0),
      taxAmount: parseFloat(row.tax_amount || 0),
      totalAmount: parseFloat(row.total_amount || 0),
      paidAmount: parseFloat(row.paid_amount || 0)
    },
    pickupOtp: row.pickup_otp || null,
    createdAt: row.created_at,
    updatedAt: row.updated_at
  };
}

class RentalService {
  // Get list of rentals with filters and pagination
  async getRentals(filters, pagination) {
    try {
      const result = await RentalRepository.getRentals(filters, pagination);
      result.rentals = (result.rentals || []).map(row => formatRentalResponse(row));
      return result;
    } catch (error) {
      logger.error('RentalService - Get Rentals Error:', error);
      throw new Error('Failed to fetch rentals');
    }
  }

  // Get rental detail by ID
  async getRentalById(rentalId) {
    try {
      const rental = await RentalRepository.findById(rentalId);
      if (!rental) {
        throw new Error('Rental not found');
      }
      return formatRentalResponse(rental);
    } catch (error) {
      logger.error(`RentalService - Get Rental By ID Error (id: ${rentalId}):`, error);
      throw error;
    }
  }

  // Generate Pickup OTP
  async generatePickupOTP(rentalId, adminId) {
    const conn = await RentalRepository.getConnection();
    try {
      await conn.beginTransaction();

      const rental = await RentalRepository.findById(rentalId, conn);
      if (!rental) {
        throw new Error('Rental not found');
      }

      if (rental.status !== 'CONFIRMED' && rental.status !== 'RESERVED' && rental.status !== 'READY_FOR_PICKUP') {
        throw new Error('Rental is not in a valid state for pickup OTP generation');
      }

      const otp = helpers.generateOTP();
      await RentalRepository.updateRental(rentalId, {
        pickup_otp: otp,
        pickup_otp_expires_at: helpers.formatMySQLDate(new Date(Date.now() + 24 * 60 * 60 * 1000))
      }, conn);

      await RentalRepository.logActivity(
        rentalId, 
        'OTP_GENERATED', 
        `Pickup OTP generated by Admin ID: ${adminId}`, 
        'ADMIN', 
        adminId, 
        conn
      );

      await conn.commit();
      return { otp };
    } catch (error) {
      await conn.rollback();
      logger.error(`RentalService - Generate OTP Error (id: ${rentalId}):`, error);
      throw error;
    } finally {
      conn.release();
    }
  }

  // Pickup Flow
  async pickupRental(rentalId, pickupData, adminId) {
    const conn = await RentalRepository.getConnection();
    try {
      await conn.beginTransaction();

      const rental = await RentalRepository.findById(rentalId, conn);
      if (!rental) {
        throw new Error('Rental not found');
      }

      // 1. Validate status
      if (rental.status !== 'CONFIRMED' && rental.status !== 'RESERVED' && rental.status !== 'READY_FOR_PICKUP' && rental.status !== 'CREATED') {
        throw new Error(`Rental status must be CREATED, CONFIRMED, RESERVED or READY_FOR_PICKUP. Current: ${rental.status}`);
      }

      // 2. Validate User
      const user = await RentalRepository.findUserById(rental.user_id, conn);
      if (!user) {
        throw new Error('Customer profile not found');
      }
      if (user.status === 'BLOCKED' || user.status === 'SUSPENDED') {
        throw new Error(`User status is ${user.status}. Rental pickup not allowed.`);
      }

      // 3. Validate Vehicle
      const vehicle = await RentalRepository.findVehicleById(rental.vehicle_id, conn);
      if (!vehicle) {
        throw new Error('Assigned vehicle not found');
      }
      if (vehicle.status !== 'AVAILABLE' && vehicle.status !== 'RENTED') {
        // RENTED is allowed if this exact rental started it, otherwise we check if it is active.
        throw new Error(`Vehicle registration ${vehicle.registration_number} is currently in status: ${vehicle.status}. Expected: AVAILABLE`);
      }

      // 4. Validate Pickup Branch
      if (pickupData.branchId) {
        const branch = await RentalRepository.findBranchById(pickupData.branchId, conn);
        if (!branch) {
          throw new Error('Pickup branch not found');
        }
      }

      // 5. Validate Payment
      if (rental.payment_status !== 'PAID' && parseFloat(rental.total_amount) > 0) {
        // Cash payment on pickup can transition it
        if (pickupData.payOnPickup && pickupData.paymentMethod) {
          await RentalRepository.createPayment({
            rental_id: rentalId,
            payment_type: 'RENTAL',
            payment_method: pickupData.paymentMethod,
            amount: rental.total_amount,
            status: 'SUCCESS',
            transaction_id: pickupData.transactionId || 'CASH_' + Date.now(),
            remarks: 'Payment collected at pickup branch'
          }, conn);
          
          await RentalRepository.updateRental(rentalId, {
            payment_status: 'PAID',
            paid_amount: rental.total_amount
          }, conn);
        } else {
          throw new Error('Rental has outstanding payment due before start');
        }
      }

      // 6. Validate OTP
      if (pickupData.otp !== rental.pickup_otp) {
        throw new Error('Invalid or incorrect pickup OTP');
      }

      // 7. Insert Vehicle Inspection
      const { inspection } = pickupData;
      await RentalRepository.createInspection({
        rental_id: rentalId,
        inspection_type: 'PRE_RENTAL',
        battery_ok: inspection.batteryOk ? 1 : 0,
        tyres_ok: inspection.tyresOk ? 1 : 0,
        brake_ok: inspection.brakeOk ? 1 : 0,
        lights_ok: inspection.lightsOk ? 1 : 0,
        body_ok: inspection.bodyOk ? 1 : 0,
        mirror_ok: inspection.mirrorOk ? 1 : 0,
        helmet_ok: inspection.helmetOk ? 1 : 0,
        fuel_level: inspection.fuelLevel || 'FULL',
        accessories: inspection.accessories ? JSON.stringify(inspection.accessories) : null,
        images: pickupData.images ? JSON.stringify(pickupData.images) : null,
        videos: pickupData.videos ? JSON.stringify(pickupData.videos) : null,
        inspector_notes: inspection.notes || 'Inspection successful',
        inspector_id: adminId
      }, conn);

      // 8. Insert Vehicle Checklist
      const { checklist } = pickupData;
      await RentalRepository.createChecklist({
        rental_id: rentalId,
        checklist_type: 'PICKUP',
        items: checklist ? JSON.stringify(checklist) : '{}',
        customer_confirmation: pickupData.customerConfirmation ? 1 : 0,
        admin_confirmation: 1,
        digital_signature: pickupData.signature
      }, conn);

      // 9. Sign Agreement
      await RentalRepository.createAgreement({
        rental_id: rentalId,
        agreement_text: `Standard Lease Agreement for vehicle registration ${vehicle.registration_number}. Customer agreed to rates and terms.`,
        customer_signature: pickupData.signature || 'DIGITALLY_SIGNED',
        signed_at: helpers.formatMySQLDate(new Date())
      }, conn);

      // 10. Held security deposit in database
      await RentalRepository.createSecurityDeposit({
        rental_id: rentalId,
        amount_held: rental.security_deposit,
        status: 'HELD'
      }, conn);

      // 11. Update Vehicle Status
      await RentalRepository.updateVehicleStatus(rental.vehicle_id, 'RENTED', conn);

      // 12. Update Rental Status to ACTIVE
      const current_time_str = helpers.formatMySQLDate(new Date());
      await RentalRepository.updateRental(rentalId, {
        status: 'ACTIVE',
        actual_start_time: current_time_str
      }, conn);

      // 13. Audit & Activity Logs
      await RentalRepository.logStatusChange(rentalId, rental.status, 'ACTIVE', 'ADMIN', adminId, 'Rental picked up by user', conn);
      await RentalRepository.logActivity(rentalId, 'PICKUP', `Vehicle registration ${vehicle.registration_number} picked up at branch. Status updated to ACTIVE.`, 'ADMIN', adminId, conn);

      await conn.commit();
      return { success: true, message: 'Pickup processed successfully', rentalId };
    } catch (error) {
      await conn.rollback();
      logger.error(`RentalService - Pickup Error (id: ${rentalId}):`, error);
      throw error;
    } finally {
      conn.release();
    }
  }

  // Return Flow
  async returnRental(rentalId, returnData, adminId) {
    const conn = await RentalRepository.getConnection();
    try {
      await conn.beginTransaction();

      const rental = await RentalRepository.findById(rentalId, conn);
      if (!rental) {
        throw new Error('Rental not found');
      }

      // 1. Validate status
      if (rental.status !== 'ACTIVE' && rental.status !== 'EXTENDED' && rental.status !== 'OVERDUE') {
        throw new Error(`Rental is not currently in an active state. Current: ${rental.status}`);
      }

      const vehicle = await RentalRepository.findVehicleById(rental.vehicle_id, conn);
      if (!vehicle) {
        throw new Error('Vehicle profile not found');
      }

      const plan = await RentalRepository.findPlanById(rental.plan_id, conn);
      
      // 2. Insert Post-Rental Inspection
      const { inspection } = returnData;
      await RentalRepository.createInspection({
        rental_id: rentalId,
        inspection_type: 'POST_RENTAL',
        battery_ok: inspection.batteryOk ? 1 : 0,
        tyres_ok: inspection.tyresOk ? 1 : 0,
        brake_ok: inspection.brakeOk ? 1 : 0,
        lights_ok: inspection.lightsOk ? 1 : 0,
        body_ok: inspection.bodyOk ? 1 : 0,
        mirror_ok: inspection.mirrorOk ? 1 : 0,
        helmet_ok: inspection.helmetOk ? 1 : 0,
        fuel_level: inspection.fuelLevel || 'FULL',
        accessories: inspection.accessories ? JSON.stringify(inspection.accessories) : null,
        images: returnData.images ? JSON.stringify(returnData.images) : null,
        videos: returnData.videos ? JSON.stringify(returnData.videos) : null,
        inspector_notes: inspection.notes || 'Return inspection successful',
        inspector_id: adminId
      }, conn);

      // 3. Insert Return Checklist
      const { checklist } = returnData;
      await RentalRepository.createChecklist({
        rental_id: rentalId,
        checklist_type: 'RETURN',
        items: checklist ? JSON.stringify(checklist) : '{}',
        customer_confirmation: returnData.customerConfirmation ? 1 : 0,
        admin_confirmation: 1,
        digital_signature: returnData.signature
      }, conn);

      // 4. Calculate return times and penalties
      const actualReturnDate = new Date();
      const expectedEndDate = new Date(rental.end_date);
      
      const penaltyInput = {
        expectedEndDate,
        actualReturnDate,
        damageCost: returnData.damageCost || 0,
        damageDescription: returnData.damageDescription,
        cleaningCost: returnData.cleaningCost || 0,
        missingAccessoriesCost: returnData.missingAccessoriesCost || 0,
        missingAccessoriesDescription: returnData.missingAccessoriesDescription,
        fuelShortageCost: returnData.fuelShortageCost || 0,
        batteryIssueCost: returnData.batteryIssueCost || 0,
        policyViolationCost: returnData.policyViolationCost || 0,
        policyViolationDescription: returnData.policyViolationDescription
      };

      const penalties = penaltyCalculator.calculateAllPenalties(penaltyInput, plan || {});

      // 5. Create penalty records in DB
      for (const penalty of penalties) {
        await RentalRepository.createPenalty({
          rental_id: rentalId,
          penalty_type: penalty.type,
          amount: penalty.amount,
          description: penalty.description,
          status: 'UNPAID'
        }, conn);
      }

      // 6. Record damage report if damage cost > 0
      if (returnData.damageCost && parseFloat(returnData.damageCost) > 0) {
        await RentalRepository.createDamageReport({
          rental_id: rentalId,
          description: returnData.damageDescription || 'Vehicle damaged during rental period',
          photos: returnData.images ? JSON.stringify(returnData.images) : null,
          videos: returnData.videos ? JSON.stringify(returnData.videos) : null,
          inspector_id: adminId,
          estimated_cost: returnData.damageCost,
          actual_cost: returnData.damageCost,
          repair_status: 'REPORTED'
        }, conn);
      }

      // 7. Calculate Invoice Breakdown
      const invoiceBreakdown = invoiceGenerator.generateBreakdown(rental, penalties);

      // 8. Security Deposit Deductions / Refunds
      const heldDeposit = await RentalRepository.findSecurityDepositByRentalId(rentalId, conn);
      if (heldDeposit) {
        const newDepositStatus = invoiceBreakdown.depositRefund === 0 
          ? 'FORFEITED' 
          : (invoiceBreakdown.depositRefund < rental.security_deposit ? 'PARTIALLY_REFUNDED' : 'REFUNDED');

        const totalDeductions = invoiceBreakdown.extraTimeCharges + invoiceBreakdown.penaltyCharges + invoiceBreakdown.damageCharges + invoiceBreakdown.cleaningCharges;
        const damageDeduction = Math.min(heldDeposit.amount_held, invoiceBreakdown.damageCharges);
        const penaltyDeduction = Math.min(Math.max(0, heldDeposit.amount_held - damageDeduction), totalDeductions - damageDeduction);

        await RentalRepository.updateSecurityDeposit(heldDeposit.deposit_id, {
          amount_refunded: invoiceBreakdown.depositRefund,
          damage_deduction: damageDeduction,
          penalty_deduction: penaltyDeduction,
          status: newDepositStatus,
          refunded_at: helpers.formatMySQLDate(actualReturnDate)
        }, conn);

        if (invoiceBreakdown.depositRefund > 0) {
          await RentalRepository.createRefund({
            rental_id: rentalId,
            amount: invoiceBreakdown.depositRefund,
            status: 'SUCCESS',
            transaction_id: 'REF_' + Date.now(),
            remarks: `Security deposit refund of ${invoiceBreakdown.depositRefund} processed`
          }, conn);
        }
      }

      // 9. Generate Invoice Number & Create Invoice
      const invoiceNumber = invoiceGenerator.generateInvoiceNumber(rentalId);
      await RentalRepository.createInvoice({
        rental_id: rentalId,
        invoice_number: invoiceNumber,
        rental_charges: invoiceBreakdown.rentalCharges,
        extra_time_charges: invoiceBreakdown.extraTimeCharges,
        penalty_charges: invoiceBreakdown.penaltyCharges,
        damage_charges: invoiceBreakdown.damageCharges,
        cleaning_charges: invoiceBreakdown.cleaningCharges,
        deposit_amount: invoiceBreakdown.depositAmount,
        discount_amount: invoiceBreakdown.discountAmount,
        tax_amount: invoiceBreakdown.taxAmount,
        total_amount: invoiceBreakdown.total,
        status: 'PAID' // Assuming paid via wallet/gateway/deposit
      }, conn);

      // 10. Update Vehicle status to AVAILABLE
      await RentalRepository.updateVehicleStatus(rental.vehicle_id, 'AVAILABLE', conn);

      // 11. Update Rental status to COMPLETED
      const return_time_str = helpers.formatMySQLDate(actualReturnDate);
      await RentalRepository.updateRental(rentalId, {
        status: 'COMPLETED',
        actual_end_time: return_time_str,
        payment_status: 'PAID',
        return_branch_id: returnData.branchId || rental.return_branch_id
      }, conn);

      // 12. Audit Logs & Activity Logs
      await RentalRepository.logStatusChange(rentalId, rental.status, 'COMPLETED', 'ADMIN', adminId, 'Rental completed and returned successfully', conn);
      await RentalRepository.logActivity(rentalId, 'RETURN', `Vehicle registration ${vehicle.registration_number} returned. Total invoice: ${invoiceBreakdown.total}. Status COMPLETED.`, 'ADMIN', adminId, conn);

      await conn.commit();
      return { success: true, message: 'Return processed successfully', invoiceNumber, total: invoiceBreakdown.total };
    } catch (error) {
      await conn.rollback();
      logger.error(`RentalService - Return Error (id: ${rentalId}):`, error);
      throw error;
    } finally {
      conn.release();
    }
  }

  // Extension Flow
  async extendRental(rentalId, extensionData, adminId) {
    const conn = await RentalRepository.getConnection();
    try {
      await conn.beginTransaction();

      const rental = await RentalRepository.findById(rentalId, conn);
      if (!rental) {
        throw new Error('Rental not found');
      }

      // 1. Verify status
      if (rental.status !== 'ACTIVE' && rental.status !== 'EXTENDED') {
        throw new Error('Rental must be ACTIVE or EXTENDED to extend');
      }

      // Determine duration values
      const duration = parseInt(extensionData.duration);
      const unit = extensionData.durationUnit; // HOURS, DAYS, WEEKS

      const currentEndDate = new Date(rental.end_date);
      let newEndDate;
      if (unit === 'hours') {
        newEndDate = new Date(currentEndDate.getTime() + duration * 60 * 60 * 1000);
      } else if (unit === 'days') {
        newEndDate = new Date(currentEndDate.getTime() + duration * 24 * 60 * 60 * 1000);
      } else if (unit === 'weeks') {
        newEndDate = new Date(currentEndDate.getTime() + duration * 7 * 24 * 60 * 60 * 1000);
      } else {
        newEndDate = new Date(currentEndDate.getTime() + duration * 24 * 60 * 60 * 1000); // Default to days
      }

      // 2. Check future reservation conflicts
      const hasConflict = await RentalRepository.checkFutureReservations(
        rental.vehicle_id, 
        helpers.formatMySQLDate(currentEndDate), 
        helpers.formatMySQLDate(newEndDate), 
        conn
      );
      if (hasConflict) {
        throw new Error('Cannot extend: Vehicle has another overlapping reservation');
      }

      // 3. Rate calculation
      const plan = await RentalRepository.findPlanById(rental.plan_id, conn);
      const extensionRate = plan ? parseFloat(plan.rate) : 200.00; // fallback rate
      const extensionCost = parseFloat((duration * extensionRate).toFixed(2));

      // 4. Create Extension payment
      if (extensionData.paymentStatus === 'PAID') {
        await RentalRepository.createPayment({
          rental_id: rentalId,
          payment_type: 'EXTENSION',
          payment_method: extensionData.paymentMethod || 'WALLET',
          amount: extensionCost,
          status: 'SUCCESS',
          transaction_id: extensionData.transactionId || 'EXT_' + Date.now(),
          remarks: `Payment for ${duration} ${unit} extension`
        }, conn);
      } else {
        throw new Error('Payment is required before performing rental extension');
      }

      // 5. Update Extension table
      await RentalRepository.createExtension({
        rental_id: rentalId,
        previous_end_date: helpers.formatMySQLDate(currentEndDate),
        new_end_date: helpers.formatMySQLDate(newEndDate),
        duration,
        duration_unit: unit.toUpperCase(),
        amount: extensionCost,
        payment_status: 'PAID',
        transaction_id: extensionData.transactionId || 'EXT_' + Date.now()
      }, conn);

      // 6. Update end_date and status on Rental
      const current_status = rental.status;
      await RentalRepository.updateRental(rentalId, {
        end_date: helpers.formatMySQLDate(newEndDate),
        status: 'EXTENDED',
        total_amount: parseFloat(rental.total_amount) + extensionCost,
        paid_amount: parseFloat(rental.paid_amount) + extensionCost
      }, conn);

      // 7. Logs
      await RentalRepository.logStatusChange(rentalId, current_status, 'EXTENDED', 'ADMIN', adminId, `Rental extended to ${helpers.formatMySQLDate(newEndDate)}`, conn);
      await RentalRepository.logActivity(rentalId, 'EXTENSION', `Rental extended by ${duration} ${unit}. Cost: ${extensionCost}.`, 'ADMIN', adminId, conn);

      await conn.commit();
      return { success: true, newEndDate: helpers.formatMySQLDate(newEndDate), cost: extensionCost };
    } catch (error) {
      await conn.rollback();
      logger.error(`RentalService - Extend Error (id: ${rentalId}):`, error);
      throw error;
    } finally {
      conn.release();
    }
  }

  // Cancel Flow
  async cancelRental(rentalId, reason, adminId) {
    const conn = await RentalRepository.getConnection();
    try {
      await conn.beginTransaction();

      const rental = await RentalRepository.findById(rentalId, conn);
      if (!rental) {
        throw new Error('Rental not found');
      }

      const validCancelStates = ['CREATED', 'PAYMENT_PENDING', 'CONFIRMED', 'RESERVED', 'READY_FOR_PICKUP'];
      if (!validCancelStates.includes(rental.status)) {
        throw new Error(`Rental cannot be cancelled from current state: ${rental.status}`);
      }

      // Update rental status
      await RentalRepository.updateRental(rentalId, {
        status: 'CANCELLED'
      }, conn);

      // Free vehicle back to AVAILABLE
      await RentalRepository.updateVehicleStatus(rental.vehicle_id, 'AVAILABLE', conn);

      // Refund security deposit if held
      const deposit = await RentalRepository.findSecurityDepositByRentalId(rentalId, conn);
      if (deposit && deposit.status === 'HELD') {
        await RentalRepository.updateSecurityDeposit(deposit.deposit_id, {
          amount_refunded: deposit.amount_held,
          status: 'REFUNDED',
          refunded_at: helpers.formatMySQLDate(new Date())
        }, conn);

        await RentalRepository.createRefund({
          rental_id: rentalId,
          amount: deposit.amount_held,
          status: 'SUCCESS',
          transaction_id: 'REF_CAN_' + Date.now(),
          remarks: 'Refund of security deposit on cancellation'
        }, conn);
      }

      // Logs
      await RentalRepository.logStatusChange(rentalId, rental.status, 'CANCELLED', 'ADMIN', adminId, `Cancelled. Reason: ${reason}`, conn);
      await RentalRepository.logActivity(rentalId, 'CANCELLATION', `Rental cancelled by admin. Reason: ${reason}`, 'ADMIN', adminId, conn);

      await conn.commit();
      return { success: true, message: 'Rental cancelled successfully' };
    } catch (error) {
      await conn.rollback();
      logger.error(`RentalService - Cancel Error (id: ${rentalId}):`, error);
      throw error;
    } finally {
      conn.release();
    }
  }

  // Force Close (Super Admin Only)
  async forceCloseRental(rentalId, reason, adminId) {
    const conn = await RentalRepository.getConnection();
    try {
      await conn.beginTransaction();

      const rental = await RentalRepository.findById(rentalId, conn);
      if (!rental) {
        throw new Error('Rental not found');
      }

      // Update Rental status
      await RentalRepository.updateRental(rentalId, {
        status: 'CANCELLED',
        actual_end_time: helpers.formatMySQLDate(new Date())
      }, conn);

      // Free vehicle
      await RentalRepository.updateVehicleStatus(rental.vehicle_id, 'AVAILABLE', conn);

      // Forfeit deposit or process refunds based on reason
      const deposit = await RentalRepository.findSecurityDepositByRentalId(rentalId, conn);
      if (deposit && deposit.status === 'HELD') {
        await RentalRepository.updateSecurityDeposit(deposit.deposit_id, {
          amount_refunded: 0,
          penalty_deduction: deposit.amount_held,
          status: 'FORFEITED',
          refunded_at: helpers.formatMySQLDate(new Date())
        }, conn);
      }

      // Logs
      await RentalRepository.logStatusChange(rentalId, rental.status, 'FORCE_CLOSED', 'ADMIN', adminId, `Force closed. Reason: ${reason}`, conn);
      await RentalRepository.logActivity(rentalId, 'FORCE_CLOSE', `Rental force closed by Super Admin. Reason: ${reason}`, 'ADMIN', adminId, conn);

      await conn.commit();
      return { success: true, message: 'Rental force closed successfully' };
    } catch (error) {
      await conn.rollback();
      logger.error(`RentalService - Force Close Error (id: ${rentalId}):`, error);
      throw error;
    } finally {
      conn.release();
    }
  }

  // Overdue Engine
  async getOverdueRentals(pagination) {
    try {
      // 1. Fetch overdue rentals
      const result = await RentalRepository.findOverdueRentals(pagination);
      
      // 2. Perform live penalty estimate for display in the response
      result.rentals = result.rentals.map(rental => {
        const lateResult = penaltyCalculator.calculateLateReturn(
          rental.end_date, 
          new Date(), 
          120.00 // standard hourly penalty rate
        );

        return {
          rentalId: rental.rental_id,
          userId: rental.user_id,
          userName: rental.user_name,
          userPhone: rental.user_phone,
          registrationNumber: rental.registration_number,
          modelName: rental.model_name,
          vehicleType: rental.vehicle_type,
          startDate: rental.start_date,
          expectedEndDate: rental.end_date,
          hoursOverdue: lateResult.hoursOverdue,
          estimatedLatePenalty: lateResult.penaltyAmount,
          status: rental.status
        };
      });

      return result;
    } catch (error) {
      logger.error('RentalService - Get Overdue Error:', error);
      throw error;
    }
  }

  // Invoice view
  async getRentalInvoice(rentalId) {
    try {
      const invoice = await RentalRepository.findInvoiceByRentalId(rentalId);
      if (!invoice) {
        throw new Error('Invoice not found for this rental');
      }
      return invoice;
    } catch (error) {
      logger.error(`RentalService - Get Invoice Error (id: ${rentalId}):`, error);
      throw error;
    }
  }

  // Payments history
  async getPaymentHistory(rentalId) {
    try {
      return await RentalRepository.getPaymentsByRentalId(rentalId);
    } catch (error) {
      logger.error(`RentalService - Get Payments Error (id: ${rentalId}):`, error);
      throw error;
    }
  }

  // Timeline
  async getTimeline(rentalId) {
    try {
      return await RentalRepository.getTimeline(rentalId);
    } catch (error) {
      logger.error(`RentalService - Get Timeline Error (id: ${rentalId}):`, error);
      throw error;
    }
  }

  // Damage report
  async getDamageReport(rentalId) {
    try {
      return await RentalRepository.findDamageReportByRentalId(rentalId);
    } catch (error) {
      logger.error(`RentalService - Get Damage Report Error (id: ${rentalId}):`, error);
      throw error;
    }
  }

  // Manual inspection registration
  async recordInspection(rentalId, inspectionData, adminId) {
    try {
      const id = await RentalRepository.createInspection({
        rental_id: rentalId,
        inspection_type: inspectionData.inspectionType || 'PRE_RENTAL',
        battery_ok: inspectionData.batteryOk ? 1 : 0,
        tyres_ok: inspectionData.tyresOk ? 1 : 0,
        brake_ok: inspectionData.brakeOk ? 1 : 0,
        lights_ok: inspectionData.lightsOk ? 1 : 0,
        body_ok: inspectionData.bodyOk ? 1 : 0,
        mirror_ok: inspectionData.mirrorOk ? 1 : 0,
        helmet_ok: inspectionData.helmetOk ? 1 : 0,
        fuel_level: inspectionData.fuelLevel || 'FULL',
        accessories: inspectionData.accessories ? JSON.stringify(inspectionData.accessories) : null,
        images: inspectionData.images ? JSON.stringify(inspectionData.images) : null,
        videos: inspectionData.videos ? JSON.stringify(inspectionData.videos) : null,
        inspector_notes: inspectionData.notes || 'Inspection registered',
        inspector_id: adminId
      });
      return { success: true, inspectionId: id };
    } catch (error) {
      logger.error(`RentalService - Record Inspection Error (id: ${rentalId}):`, error);
      throw error;
    }
  }

  // Manual checklist registration
  async recordChecklist(rentalId, checklistData, adminId) {
    try {
      const id = await RentalRepository.createChecklist({
        rental_id: rentalId,
        checklist_type: checklistData.checklistType || 'PICKUP',
        items: checklistData.items ? JSON.stringify(checklistData.items) : '{}',
        customer_confirmation: checklistData.customerConfirmation ? 1 : 0,
        admin_confirmation: checklistData.adminConfirmation ? 1 : 0,
        digital_signature: checklistData.digitalSignature
      });
      return { success: true, checklistId: id };
    } catch (error) {
      logger.error(`RentalService - Record Checklist Error (id: ${rentalId}):`, error);
      throw error;
    }
  }
}

module.exports = new RentalService();

