module.exports = {
  ERRORS: {
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    BAD_REQUEST: "BAD_REQUEST",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  },
};
